GRANT ALL PRIVILEGES ON *.* TO 'dbadmin'@'%' IDENTIFIED BY 'dbadmin' WITH GRANT OPTION;
create database tvshows ;
use tvshows ;
CREATE TABLE tvshows (id INT not null AUTO_INCREMENT, name VARCHAR (30) not null , finale VARCHAR (100), image VARCHAR (30), PRIMARY KEY (id));
insert into tvshows  values (0, 'breaking bad','brother in law turns to be a dealer','graphical/81189-g21.jpg');
insert into tvshows  values (0, 'game of thrones','lord of the knight is hired to refresh spain','graphical/5ca9a495dd45f.jpg');
insert into tvshows  values (0, 'friends','ross marries rachel','graphical/79168-g5.jpg');
insert into tvshows  values (0, 'lady bug','marinette is hakumatized','text/302218.jpg');
insert into tvshows  values (0, 'ally mcbeal','ally marries with the doctor','graphical/72116-g.jpg');
insert into tvshows  values (0, 'seinfeld','they have this big adventure and...yada yada','');
insert into tvshows  values (0, 'smallville','damn clark finally flies in the last 10mn','');
